version: '3'
services:
  web:
    build: .
    container_name: backend_socialnet
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env  # Загрузить переменные из .env

  db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USERNAME}       # Сопоставляем переменные из .env
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    container_name: watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=1800
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json

volumes:
  postgres_data:
